#!/bin/bash

if [ "${DIB_DEBUG_TRACE:-1}" -gt 0 ]; then
    set -x
fi
set -u
set -o pipefail

sudo rm -f $TARGET_ROOT/etc/default/grub.d/50-cloudimg-settings.cfg && echo "Successfully removed /etc/default/grub.d/50-cloudimg-settings.cfg" || true
