#!/bin/bash

if [ ${DIB_DEBUG_TRACE:-0} -gt 0 ]; then
    set -x
fi
set -eu
set -o pipefail


# ipv6.disable=1 net.ifnames=0 biosdevname=0
echo 'GRUB_CMDLINE_LINUX="${GRUB_CMDLINE_LINUX} ipv6.disable=1 net.ifnames=0 biosdevname=0"' >> /etc/default/grub

